//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace memes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth
    {
        public int Id { get; set; }
        public string Gender { get; set; }
        public int CategoryId { get; set; }
        public string Brand { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public decimal Price { get; set; }
        public byte[] Image { get; set; }
        public string MoreDetails { get; set; }
        public string BrandInfo { get; set; }
        public string LookAfter { get; set; }
        public string About { get; set; }
        public string Color { get; set; }
        public byte[] ExtraImage { get; set; }
        public string style { get; set; }
    }
}
